export const SPORTS ={
    cricket:[
        {
            Country:"India",
            logo:"assets/images/India.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
        },
        {
            Country:"Australia",
            logo:"assets/images/Aus.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
            
        },
        {
            Country:"England",
            logo:"assets/images/ENg.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
        },
        {
            Country:"South Africa",
            logo:"assets/images/SA.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
        },
        {
            Country:"England",
            logo:"assets/images/ENg.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
        },
        {
            Country:"South Africa",
            logo:"assets/images/SA.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
           
        }
    ],
    football:[
        {
            Country:"Brazil",
            logo:"assets/images/India.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
            
        },
        {
            Country:"Spain",
            logo:"assets/images/Aus.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
           
        },
        {
            Country:"Argentina",
            logo:"assets/images/ENg.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
           
        },
        {
            Country:"Urugve",
            logo:"assets/images/SA.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ]    
        },
        {
            Country:"France",
            logo:"assets/images/ENg.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
            
        },
        {
            Country:"Croatia",
            logo:"assets/images/SA.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"}
            ],
           
        }
    ],
    hockey:[
        {
            Country:"Spain",
            logo:"assets/images/India.png",
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                
            ],
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"]
        },
        {
            Country:"Russia",
            logo:"assets/images/Aus.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
               
            ],
            
        },
        {
            Country:"France",
            logo:"assets/images/ENg.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                
            ],
            
        },
        {
            Country:"Serbia",
            logo:"assets/images/SA.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
               
            ],
            
        },
        {
            Country:"Germany",
            logo:"assets/images/ENg.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
            ],
            
        },
        {
            Country:"United States",
            logo:"assets/images/SA.png",
            videos:["Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY","Lz5098-SeFY"],
            Player:[
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
                {Name:"abc",imgUrl:"assets/images/dummyprofile.jpeg"},
            
            ],
           
        }
    ]
}